version: '3.8'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: todolist
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: .
    environment:
      POSTGRES_DB: todolist
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_HOST: db
    ports:
      - "5000:5000"
    depends_on:
      - db

volumes:
  postgres_data: